[proxy]
domain = "local.dev"
usegzip = "true"

routes = [
    {path="/",destination="http://localhost:6000/"},
    {path="/home",destination="http://localhost:5000"},
    {path="/app",destination="http://localhost:4000"},
]

